CUDA_VISIBLE_DEVICES=0 python3 src/test.py\
    --batch_size=256\
    --window_size=32\
    --stride_size=32\
    --gpu\
    --k=0.10\
    --num_blocks=1\
    --st_units=16\
    --example=2\
    --dataset=WADI\
    --wavelet_type=coif2\
    --N=32\
    --heads=1\
    --seed=6\
    --name=WaveletNF_wadi_seed_6